# To install:
#   brew tap homebrew/bundle
#   brew bundle

brew "ssh-copy-id"
brew "tig"
brew "wget"
brew "watch"
brew "ctags"
brew "the_silver_searcher"
brew "tree"
brew "fzf"
brew "colordiff"

cask_args appdir: '/Applications'
cask 'caffeine'
cask 'flux'
cask 'iterm2'
